rAthena rev16510

diff --git a/emulador/configure.in b/emulador/configure.in
--- a/emulador/configure.in
+++ b/emulador/configure.in
@@ -1,15 +1,17 @@
 #                                               -*- Autoconf -*-
 # Process this file with autoconf to produce a configure script.
 
-AC_INIT(eAthena)
-AC_REVISION($Revision: 13486 $)
+AC_INIT(rAthena)
+AC_REVISION($Revision: 16271 $)
 AC_PREREQ([2.59])
 AC_CONFIG_SRCDIR([src/common/cbasetypes.h])
 AC_CONFIG_FILES([Makefile src/common/Makefile])
-AC_CONFIG_FILES([src/char/Makefile src/login/Makefile src/ladmin/Makefile])
-AC_CONFIG_FILES([src/char_sql/Makefile src/txt-converter/Makefile])
-AC_CONFIG_FILES([src/map/Makefile src/plugins/Makefile src/tool/Makefile])
+AC_CONFIG_FILES([3rdparty/mt19937ar/Makefile 3rdparty/libconfig/Makefile])
+AC_CONFIG_FILES([src/char/Makefile src/login/Makefile])
+AC_CONFIG_FILES([src/map/Makefile src/tool/Makefile])
+AC_CONFIG_FILES([src/test/Makefile])
 
+AC_GNU_SOURCE
 
 #
 # Memory managers
@@ -74,6 +76,50 @@ AC_ARG_ENABLE(
 	[enable_debug="no"]
 )
 
+#
+# Buildbot
+#
+AC_ARG_ENABLE(
+	[buildbot],
+	AC_HELP_STRING(
+		[--enable-buildbot@<:@=ARG@:>@],
+		[(available options: yes, no)]
+	),
+	[
+		enable_buildbot="$enableval"
+		case $enableval in
+			"no");;
+			"yes");;
+			*) AC_MSG_ERROR([[invalid argument --enable-buildbot=$enableval... stopping]]);;
+		esac
+	],
+	[enable_buildbot="no"]
+)
+
+#
+# RDTSC as Tick Source 
+#
+AC_ARG_ENABLE(
+	[rdtsc],
+	AC_HELP_STRING(
+		[--enable-rdtsc],
+		[
+			Uses rdtsc as timing source (disabled by default)
+			Enable it when you've timing issues.
+
+			(For example:  in conjunction with XEN or Other Virtualization mechanisms)
+		
+			Note:
+				Please ensure that you've disabled dynamic CPU-Frequencys, such as power saving options.
+				(On the most modern Dedicated Servers cpufreq is preconfigured, see your distribution's manual
+				 how to disable it)
+		]
+	),
+	[
+		enable_rdtsc=1
+	],
+	[enable_rdtsc=0]
+)
 
 #
 # Profiler
@@ -102,10 +148,9 @@ AC_ARG_ENABLE(
 AC_ARG_ENABLE(
 	[64bit],
 	AC_HELP_STRING(
-		[--enable-64bit],
+		[--disable-64bit],
 		[
-			Don't force 32 bit. (disabled by default)
-			64bit support is still being tested, not recommended for production servers.
+			Enforce 32bit output on x86_64 systems.
 		]
 	),
 	[
@@ -116,34 +161,78 @@ AC_ARG_ENABLE(
 			*) AC_MSG_ERROR([[invalid argument --enable-64bit=$enableval... stopping]]);;
 		esac
 	],
-	[enable_64bit="no"]
+	[enable_64bit="yes"]
 )
 
 
 #
-# Enable/disable MySql and optionally specify the path to mysql_config (optional library)
+# LTO
+#
+AC_ARG_ENABLE(
+    [lto],
+    AC_HELP_STRING(
+        [--enable-lto],
+        [
+			Enables or Disables Linktime Code Optimization (LTO is enabled by default)
+        ]
+    ),
+    [
+        enable_lto="$enableval"
+        case $enableval in
+            "no");;
+            "yes");;
+            *) AC_MSG_ERROR([[invalid argument --enable-lto=$disableval... stopping]]);;
+        esac
+    ],
+    [enable_lto="yes"]
+)
+
+
+#
+# Optionally set the max number of network conenctions
+# the core will be support
+#
+AC_ARG_WITH(
+	[maxconn],
+	AC_HELP_STRING(
+		[--with-maxconn@<:@=ARG@:>@],
+		[optionally set the maximum connections the core can handle (default: 16384) NOT USED YET - EXPERIMENTAL]
+	),
+	[
+		if test "$withval" == "no";	 then
+			CFLAGS="$CFLAGS -DMAXCONN=16384"	
+		else
+			
+			if ! test "$withval" -ge 0 -o "$withval" -lt 0 2>&- ; then
+				AC_MSG_ERROR([Invalid argument --with-maxconn=$withval ... stopping])
+			else
+				CFLAGS="$CFLAGS -DMAXCONN=$withval"
+			fi
+		fi
+	],
+	[
+		CFLAGS="$CFLAGS -DMAXCONN=16384"
+	]
+)
+
+
+#
+# Optionally specify the path to mysql_config
 #
 AC_ARG_WITH(
 	[mysql],
 	AC_HELP_STRING(
 		[--with-mysql@<:@=ARG@:>@],
-		[use MySQL client library, optionally specify the path to the mysql_config executable (by default mysql is used if found)]
+		[optionally specify the path to the mysql_config executable]
 	),
 	[
-		if test "$withval" = "no" ; then
-			want_mysql="no"
-		else
-			want_mysql="yes"
-			require_mysql="yes"
-			if test "$withval" != "yes" ; then
-				if test ! -x "$withval" ; then
-					AC_MSG_ERROR([$withval is not an executable file])
-				fi
-				MYSQL_CONFIG_HOME="$withval"
+		if test "$withval" != "no" ; then
+			if test ! -x "$withval" ; then
+				AC_MSG_ERROR([$withval is not an executable file])
 			fi
+			MYSQL_CONFIG_HOME="$withval"
 		fi
-	],
-	[want_mysql="yes" require_mysql="no"]
+	]
 )
 
 
@@ -238,6 +327,7 @@ AC_ARG_WITH(
 AC_PROG_MAKE_SET
 AC_PROG_CC
 AC_PROG_CPP
+AC_PATH_PROG(AR, ar)
 AC_LANG([C])
 
 
@@ -276,6 +366,55 @@ if test "$enable_64bit" = "no" ; then
 fi
 
 
+# 
+# check if we're producing 32bit code - so well produce binarys for at least i686 (speedup: cmovs, and cmpchg8 support)
+#
+AC_MSG_CHECKING([whether $CC produces 32bit code])
+AC_RUN_IFELSE(
+	[
+		int main(int argc, char **argv){
+			if(sizeof(void*) == 4) return 0;
+			else return 1;
+		}
+	],
+	[
+		AC_MSG_RESULT([yes])
+		CFLAGS="$CFLAGS -march=i686"
+		LDFLAGS="$LDFLAGS -march=i686"
+	],
+	[
+		AC_MSG_RESULT([no])
+	],
+	[
+		AC_MSG_RESULT([guessing no])
+	]
+)
+
+
+# 
+# Check if CC supports __thread attribute (Thread Local Storage) 
+# (Usually our OSX friends 're lacking support of it in older llvm versions ..)
+# 
+AC_MSG_CHECKING([whether $CC supports __thread specifier (TLS)])
+AC_RUN_IFELSE(
+	[
+		__thread int g_Test = -1;
+
+		int main(int argc, char **argv){
+			g_Test = 0;
+			return g_Test;		
+		}
+	],
+	[
+		AC_MSG_RESULT([yes])
+		CFLAGS="$CFLAGS -DHAS_TLS"
+	],
+	[
+		AC_MSG_RESULT([no])
+	]
+)
+
+
 AC_MSG_CHECKING([whether $CC supports -Wno-unused-parameter])
 OLD_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -Wno-unused-parameter"
@@ -289,12 +428,63 @@ AC_COMPILE_IFELSE(
 )
 
 
+#
+# LTO Support test
+#
+if test "$enable_lto" != "no" ; then
+
+	OLD_CFLAGS="$CFLAGS"
+	CFLAGS="$CFLAGS -flto"
+
+	OLD_LDFLAGS="$LDFLAGS"
+	LDFLAGS="$LDFLAGS -flto"
+
+	AC_MSG_CHECKING([whether $CC supports -flto])
+	AC_RUN_IFELSE(
+		[
+			int main(int argc, char **argv){
+               return 0;
+           }
+		],
+		[
+			AC_MSG_RESULT([yes])
+		],
+		[
+			AC_MSG_RESULT([no])
+			CFLAGS="$OLD_CFLAGS"
+			LDFLAGS="$OLD_LDFLAGS"
+		],
+		[
+			AC_MSG_RESULT([guessing no])
+		]
+	)
+fi
+
+
+
 AC_MSG_CHECKING([whether $CC supports -Wno-pointer-sign])
 OLD_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -Wno-pointer-sign"
 AC_COMPILE_IFELSE(
 	[int foo;],
-	[AC_MSG_RESULT([yes])],
+	[
+		AC_MSG_RESULT([yes])
+		AC_MSG_CHECKING([whether $CC can actually use -Wno-pointer-sign])
+		# This option causes warnings in C++ mode
+		# Note: -Werror must be before -Wno-pointer-sign, otherwise it does not do anything
+		CFLAGS="$OLD_CFLAGS -Werror -Wno-pointer-sign"
+		AC_COMPILE_IFELSE(
+			[int foo;],
+			[
+				AC_MSG_RESULT([yes])
+				CFLAGS="$OLD_CFLAGS -Wno-pointer-sign"
+			],
+			[
+				AC_MSG_RESULT([no])
+				CFLAGS="$OLD_CFLAGS"
+			]
+		)
+	],
 	[
 		AC_MSG_RESULT([no])
 		CFLAGS="$OLD_CFLAGS"
@@ -315,6 +505,38 @@ AC_COMPILE_IFELSE(
 )
 
 
+AC_MSG_CHECKING([whether $CC supports -fPIC])
+OLD_CFLAGS="$CFLAGS"
+CFLAGS="$CFLAGS -fPIC"
+AC_COMPILE_IFELSE(
+	[int foo;],
+	[
+		AC_MSG_RESULT([yes])
+		compiler_supports_pic="yes"
+	],
+	[
+		AC_MSG_RESULT([no])
+		compiler_supports_pic="no"
+	]
+)
+CFLAGS="$OLD_CFLAGS"
+
+
+#
+# -O2 implies -fstrict-aliasing, but the code is not safe for that
+#
+AC_MSG_CHECKING([whether $CC supports -fno-strict-aliasing])
+OLD_CFLAGS="$CFLAGS"
+CFLAGS="$CFLAGS -fno-strict-aliasing"
+AC_COMPILE_IFELSE(
+	[int foo;],
+	[AC_MSG_RESULT([yes])],
+	[
+		AC_MSG_RESULT([no])
+		CFLAGS="$OLD_CFLAGS"
+	]
+)
+
 
 ###############################################################################
 # Check for libraries and header files.
@@ -327,6 +549,16 @@ AC_COMPILE_IFELSE(
 AC_CHECK_FUNC([setrlimit],[CFLAGS="$CFLAGS -DHAVE_SETRLIMIT"])
 
 
+#
+# strnlen - string length with upper scan bound
+#
+AC_CHECK_FUNC([strnlen],[CFLAGS="$CFLAGS -DHAVE_STRNLEN"])
+
+# libconfig
+AC_CHECK_FUNCS([uselocale])
+AC_CHECK_FUNCS([newlocale])
+AC_CHECK_FUNCS([freelocale])
+AC_CHECK_HEADERS([xlocale.h])
 
 #
 # Memory manager
@@ -382,6 +614,30 @@ case $enable_debug in
 		;;
 esac
 
+#
+# Buildbot
+#
+case $enable_buildbot in
+	"no")
+		# default value
+		;;
+	"yes")
+		CFLAGS="$CFLAGS -DBUILDBOT"
+		;;
+esac
+
+#
+# RDTSC
+#
+case $enable_rdtsc in
+	0)
+		#default value
+		;;
+	1)
+		CFLAGS="$CFLAGS -DENABLE_RDTSC"
+		;;
+esac
+
 
 #
 # Profiler
@@ -411,62 +667,100 @@ AC_CHECK_HEADER([zlib.h], [], [AC_MSG_ERROR([zlib header not found, please speci
 #
 # math library (required)
 #
-AC_CHECK_LIB([m], [sqrt], [], [AC_MSG_ERROR([math library not found... stopping])])
+AC_SEARCH_LIBS([sqrt], [m], [], [AC_MSG_ERROR([math library not found... stopping])])
 
 
 #
-# clock_gettime (rt on Debian)
+# clock_gettime (optional, rt on Debian)
 #
-AC_CHECK_LIB([rt], [clock_gettime])
+AC_SEARCH_LIBS([clock_gettime], [rt])
 
 
 #
-# MySQL library (optional)
+# CLOCK_MONOTONIC clock for clock_gettime
+# Normally defines _POSIX_TIMERS > 0 and _POSIX_MONOTONIC_CLOCK (for posix
+# compliant systems) and __FreeBSD_cc_version >= 500005 (for FreeBSD
+# >= 5.1.0, which does not have the posix defines (ref. r11983)) would be
+# checked but some systems define them even when they do not support it
+# (ref. bugreport:1003).
+#
+if test "$ac_cv_search_clock_gettime" != "no" ; then
+	AC_MSG_CHECKING([whether CLOCK_MONOTONIC is supported and works])
+	AC_RUN_IFELSE(
+		[
+			#include <sys/time.h>
+			#include <time.h>
+			#include <unistd.h>
+			
+			int main(int argc, char** argv)
+			{
+				struct timespec tval;
+				return clock_gettime(CLOCK_MONOTONIC, &tval);
+			}
+		],
+		[
+			AC_MSG_RESULT([yes])
+			CFLAGS="$CFLAGS -DHAVE_MONOTONIC_CLOCK"
+		],
+		[
+			# either it failed to compile (CLOCK_MONOTONIC undefined)
+			# or clock_gettime has returned a non-zero value
+			AC_MSG_RESULT([no])
+		],
+		[
+			AC_MSG_RESULT([guessing no])
+		]
+	)
+fi
+
+
+#
+# pthread
+#
+AC_CHECK_LIB([pthread], [pthread_create], [], [AC_MSG_ERROR([pthread library not found or incompatible])])
+AC_CHECK_LIB([pthread], [pthread_sigmask], [], [AC_MSG_ERROR([pthread library not found or incompatible])])
+AC_CHECK_LIB([pthread], [pthread_attr_init], [], [AC_MSG_ERROR([pthread library not found or incompatible])])
+AC_CHECK_LIB([pthread], [pthread_attr_setstacksize], [], [AC_MSG_ERROR([pthread library not found or incompatible])])
+AC_CHECK_LIB([pthread], [pthread_attr_destroy], [], [AC_MSG_ERROR([pthread library not found or incompatible])])
+AC_CHECK_LIB([pthread], [pthread_cancel], [], [AC_MSG_ERROR([pthread library not found or incompatible])])
+AC_CHECK_LIB([pthread], [pthread_join], [], [AC_MSG_ERROR([pthread library not found or incompatible])])
+
+LDFLAGS="$LDFLAGS -lpthread"
+
+
+#
+# MySQL library
 #
 
-if test "$want_mysql" = "no" ; then
-	MYSQL_VERSION=""
-	MYSQL_CFLAGS=""
-	MYSQL_LIBS=""
-	AC_MSG_NOTICE([ignoring MySQL (optional)])
+if test -z "$MYSQL_CONFIG_HOME"; then
+	AC_PATH_PROG([MYSQL_CONFIG_HOME], [mysql_config], [no])
+fi
+
+if test "$MYSQL_CONFIG_HOME" != "no" ; then
+	MYSQL_VERSION="`$MYSQL_CONFIG_HOME --version`"
+	if test "$manual_MYSQL_CFLAGS" = "no" ; then
+		MYSQL_CFLAGS="`$MYSQL_CONFIG_HOME --include`"
+	fi
+	if test "$manual_MYSQL_LIBS" = "no" ; then
+		MYSQL_LIBS="`$MYSQL_CONFIG_HOME --libs`"
+	fi
 else
-	if test -z "$MYSQL_CONFIG_HOME"; then
-		AC_PATH_PROG([MYSQL_CONFIG_HOME], [mysql_config], [no])
-	fi
+	MYSQL_VERSION="unknown"
+fi
 
-	if test "$MYSQL_CONFIG_HOME" != "no" ; then
-		MYSQL_VERSION="`$MYSQL_CONFIG_HOME --version`"
-		if test "$manual_MYSQL_CFLAGS" = "no" ; then
-			MYSQL_CFLAGS="`$MYSQL_CONFIG_HOME --include`"
-		fi
-		if test "$manual_MYSQL_LIBS" = "no" ; then
-			MYSQL_LIBS="`$MYSQL_CONFIG_HOME --libs`"
-		fi
-	else
-		MYSQL_VERSION="unknown"
-	fi
+MYSQL_OLD_LDFLAGS="$LDFLAGS" ; LDFLAGS="$LDFLAGS $MYSQL_LIBS"
+MYSQL_OLD_CPPFLAGS="$CPPFLAGS" ; CPPFLAGS="$CPPFLAGS $MYSQL_CFLAGS"
+AC_CHECK_LIB([mysqlclient], [mysql_init], [HAVE_MYSQL="yes"], [])
+AC_CHECK_HEADER([mysql.h], [], [HAVE_MYSQL=""])
+CPPFLAGS="$MYSQL_OLD_CPPFLAGS"
+LDFLAGS="$MYSQL_OLD_LDFLAGS"
 
-	MYSQL_OLD_LDFLAGS="$LDFLAGS" ; LDFLAGS="$LDFLAGS $MYSQL_LIBS"
-	MYSQL_OLD_CPPFLAGS="$CPPFLAGS" ; CPPFLAGS="$CPPFLAGS $MYSQL_CFLAGS"
-	AC_CHECK_LIB([mysqlclient], [mysql_init], [HAVE_MYSQL="yes"], [])
-	AC_CHECK_HEADER([mysql.h], [], [HAVE_MYSQL=""])
-	CPPFLAGS="$MYSQL_OLD_CPPFLAGS"
-	LDFLAGS="$MYSQL_OLD_LDFLAGS"
-
-	AC_MSG_CHECKING([MySQL library (optional)])
-	if test "$HAVE_MYSQL" = "yes" ; then
-		AC_MSG_RESULT([yes ($MYSQL_VERSION)])
-	else
-		AC_MSG_RESULT([no])
-		if test "$require_mysql" = "yes" ; then
-			AC_MSG_ERROR([MySQL not found or incompatible (requested)])
-		else
-			AC_MSG_NOTICE([disabling MySQL (optional)])
-			MYSQL_VERSION=""
-			MYSQL_CFLAGS=""
-			MYSQL_LIBS=""
-		fi
-	fi
+AC_MSG_CHECKING([MySQL library (required)])
+if test "$HAVE_MYSQL" = "yes" ; then
+	AC_MSG_RESULT([yes ($MYSQL_VERSION)])
+else
+	AC_MSG_RESULT([no])
+	AC_MSG_ERROR([MySQL not found or incompatible])
 fi
 
 AC_SUBST([HAVE_MYSQL])
